
name: PyPI Pipeline

on:
  push:
    tags:
      - "v*"  # Runs only on version tags, e.g., v0.1.0

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install build tools
        run: pip install build

      - name: Build package
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: package
          path: dist/

  publish_testpypi:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist/

      - name: Publish to TestPyPI
        env:
          TEST_PYPI_API_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload --repository testpypi dist/* -u __token__ -p $TEST_PYPI_API_TOKEN

  publish_pypi:
    needs: publish_testpypi
    runs-on: ubuntu-latest
    environment: release  # Requires manual approval in GitHub

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: package
          path: dist/

      - name: Publish to PyPI
        env:
          PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          pip install twine
          twine upload dist/* -u __token__ -p $PYPI_API_TOKEN
